Added conversations page
NikoVe96/Elder-Friendly-Chat-Group-5 pull request #2
Opened 2023-11-09 10:01 UTC by NikoVe96

2023-11-09 15:50 UTC, NikoVe96 commented
@mircealungu

2023-11-12 15:33 UTC, igawaclawska commented on src/Conversations.js
> +                        <image src="Images/man-avatar.png" alt="avatar" width="60" height="60" class="img"></image>
The `<image>` tag is not a valid tag. Use `<img>` instead.

2023-11-12 16:00 UTC, igawaclawska commented on src/MainPage.js
> +                        <img className="img" src="/src/images/add_contact.png" alt="conversations"></img>
I've observed that there seems to be a problem with displaying images in the app (At least on my end). 

To fix it, try the following solution:

- Go to the "public" directory and create an " images " folder in there.

- Place all visual assets in this newly created "images" folder.

- Whenever you need to use images in your components or pages, use this pattern for their paths:  `src="images/image_name.format"`
(For instance:`<img className="img" src="images/add_contact.png" alt="conversations"></img>`)

Let me know if it helped :)

2023-11-12 16:09 UTC, igawaclawska commented on src/MainPage.js
> +                    <button className="settingsButton"> Settings</button>
Consider using kebab-case for CSS selectors (e.g., settings-button)
https://github.com/itu-tid/lecture-notes/blob/main/Tech-TopUps/5-Coding-Practices.md#name-your-css-classes-with-kebab-case

2023-11-12 16:22 UTC, igawaclawska requested changes
Looks good!
I've added a few change requests. Try to implement them and tag us once you are done :)

2023-12-11 11:06 UTC, closed without merging